apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: {{ .Values.service1.replicaCount }}
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: {{ .Values.service1.image }}
        ports:
        - containerPort: {{ .Values.service1.servicePort }}
