apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: LoadBalancer
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service2.servicePort }}
